### ISSUE TITLE
Question: How long does scanning typically take?

### ISSUE THREAD

**Issue by Spokehedz** [andrebrait/1g1r-romset-generator#20]
I'm just wondering if there is something wrong with my setup because it seems to be taking a very long time to scan.

**Comment by andrebrait** [comment]
It depends a lot.

What computer do you have?
Is the folder being scanned on a SSD/flash drive or a  hard disk?
Are you pointing the input directory at a folder thar has many subfolders/big subdirectory structure?
Are there zipped files?
Any particular file is taking longer?

From the way I sort the files to be scanned, the first ones usually take longer than the last ones because I distribute the bigger files among the threads first.

**Comment by Spokehedz** [comment]
Ah, apparently running it from the CMD/powershell rather than the IDE speeds it up to seconds, versus an hour plus...

Well don't I feel stupid.
