### ISSUE TITLE
Filter before downloading a set

### ISSUE THREAD

**Issue by MrGlasspoole** [andrebrait/1g1r-romset-generator#7]
Just found your filter and wonder how you update the sets?

If i understand it right your tool throws away the files you already have?
What if there is a update? That means you need to download all the files again to verify it against the No-Intro DAT to then delete them?

Is there no way to create a custom DAT and then just download the games you need?

**Comment by andrebrait** [comment]
I might have to add clarifications on the README.

The _only_ thing this program does is generating a 1G1R set from a pre-existing, curated and organized ROM set using the No-Intro naming convention. 

So, let's say you already use ClrMamePro to maintain your collection, or that you downloaded a full set from somewhere, and you want to generate a new 1G1R set from your collection. What people would normally do is use ClrMamePro for that. However, there are several issues with it, which is why I created this tool.

This tool solves one problem only: generating 1G1R sets.

So, to make things clear:

1. It only works with a pre-existing ROM collection that you either downloaded from somewhere or you maintain yourself using a ROM management tool
2. Its inputs are:
    1. Your ROM collection (optional)
    2. A Parent/Clone XML DAT
3. It outputs (by copying or moving files) a 1G1R set to a folder of your choosing.
4. It does not download ROMs
5. It does not delete files (it can **move** instead of **copying**, if you want, but it will never delete anything)
6. It does not rename files or anything. So if there's a change in naming or something, you should first update and curate your set and then use this tool.
7. It uses purely file names and simple file operations. It does not use checksums, for example.

Anything related to acquiring the ROMs or curating them is out of the scope of this tool.

**Comment by MrGlasspoole** [comment]
Sure it does not download ROMs :-)

So if you update your set (because there is a new DAT) you download everything again?

Why not generate a custom DAT in the first place with only what you want?

**Comment by andrebrait** [comment]
Well, you can generate a DAT yourself :-) it's just XML.

What seems to be unclear here is what the DAT _is_. It is the source of truth regarding which games are clones of other games. It's through the DAT that I can know that `Lylat Wars (Europe)` is `Star Fox (USA)`. Generating a DAT with just what you want could be done, but that has to be a manual process. The tool accepts the DAT and, though it does add some intelligence to fix some potential issues in the DAT itself, it depends solely on the DAT to do its job.

And I still don't know how it could be used so you wouldn't have to redownload everything.

Usually, if there's an update, then unless you're using a ROM management tool yourself and update your collection manually, you would download the whole set again.

However, if there's any mismatches or something, the tool will warn you and you can then look into how to fix your ser yourself by renaming a file or downloading a single one from an archive, for example.

Or am I still not getting what you're trying to express?

**Comment by andrebrait** [comment]
Closing this issue since this falls out of the scope of this tool
